# PLAYER STATS
player.initialLives = 5
player.speed = 8
player.shootCooldown = 15
player.hitInvincibilityTime = 120
player.image = player.png
player.posY = 50.0

# SCORING
score.gotHit = 0
score.gotPowerup = 50
score.destroyedEnemy.regular = 10
score.destroyedEnemy.strafing = 20
score.destroyedEnemy.shooting = 30
score.hitProjectile = 5
score.waveCompleted = 100

# WAVE 1: Slow, sparse enemies
wave.1.enemy.0.type = regular
wave.1.enemy.0.arrivalTime = 60
wave.1.enemy.0.posX = 400.0
wave.1.enemy.0.movementSpeed = 2

wave.1.powerup.0.type = shield
wave.1.powerup.0.arrivalTime = 300
wave.1.powerup.0.posX = 400.0

# WAVE 2: Introducing lateral movement
wave.2.enemy.0.type = regular
wave.2.enemy.0.arrivalTime = 30
wave.2.enemy.0.posX = 200.0
wave.2.enemy.0.movementSpeed = 2

wave.2.enemy.1.type = strafing
wave.2.enemy.1.arrivalTime = 150
wave.2.enemy.1.posX = 600.0
wave.2.enemy.1.movementSpeed = 3

wave.2.powerup.0.type = life
wave.2.powerup.0.arrivalTime = 400
wave.2.powerup.0.posX = 300.0

# WAVE 3: Introducing the shooter
wave.3.enemy.0.type = shooting
wave.3.enemy.0.arrivalTime = 60
wave.3.enemy.0.posX = 400.0
wave.3.enemy.0.movementSpeed = 1
enemy.shooting.firingRate = 120

wave.3.enemy.1.type = regular
wave.3.enemy.1.arrivalTime = 180
wave.3.enemy.1.posX = 200.0
wave.3.enemy.1.movementSpeed = 2

wave.3.enemy.2.type = regular
wave.3.enemy.2.arrivalTime = 220
wave.3.enemy.2.posX = 600.0
wave.3.enemy.2.movementSpeed = 2
