# WINDOW & RENDER DEFAULTS
window.width = 800
window.height = 600
background.colour = 10.0, 10.0, 20.0
text.font = upheaval.fnt
text.size = 24
text.colour = 255.0, 255.0, 255.0

# START SCREEN
start.title.text = SHADOW ALIENS
start.title.size = 48
start.title.posY = 400.0
start.instructionsList.text = PRESS 1 FOR EASY, PRESS 2 FOR MEDIUM, PRESS 3 FOR HARD
start.instructionsList.startPosY = 200.0
start.instructionsList.rowGap = 40.0

# PAUSE SCREEN
pausedTitle.text = PAUSED
pausedTitle.posY = 400.0
pausedTitle.size = 48
controlsList.text = A/D TO MOVE, SPACE TO SHOOT, G/F FOR SPEED, I FOR INVINCIBLE
controlsList.startPosY = 250.0
controlsList.rowGap = 30.0
timescale.text = CURRENT TIMESCALE:
timescale.pos = 30.0, 100.0

# END SCREEN
end.win.text = YOU WIN!
end.win.size = 48
end.win.posY = 400.0
end.lose.text = GAME OVER
end.lose.size = 48
end.lose.posY = 400.0
end.instructionsList.text = PRESS SPACE TO RESTART
end.instructionsList.startPosY = 200.0
end.instructionsList.rowGap = 30.0
