# PLAYER STATS
player.initialLives = 1
player.speed = 5
player.shootCooldown = 40
player.hitInvincibilityTime = 30
player.image = player.png
player.posY = 50.0

# SCORING
score.gotHit = 200
score.gotPowerup = 250
score.destroyedEnemy.regular = 100
score.destroyedEnemy.strafing = 150
score.destroyedEnemy.shooting = 200
score.hitProjectile = 50
score.waveCompleted = 1000

# WAVE 1: Fast swarm, immediate shooting
wave.1.enemy.0.type = shooting
wave.1.enemy.0.arrivalTime = 10
wave.1.enemy.0.posX = 100.0
wave.1.enemy.0.movementSpeed = 6
enemy.shooting.firingRate = 45

wave.1.enemy.1.type = shooting
wave.1.enemy.1.arrivalTime = 10
wave.1.enemy.1.posX = 700.0
wave.1.enemy.1.movementSpeed = 6

wave.1.powerup.0.type = engine
wave.1.powerup.0.arrivalTime = 600
wave.1.powerup.0.posX = 400.0

# WAVE 2: Crossfire
wave.2.enemy.0.type = shooting
wave.2.enemy.0.arrivalTime = 30
wave.2.enemy.0.posX = 200.0
wave.2.enemy.0.movementSpeed = 3
wave.2.enemy.shooting.firingRate = 40

wave.2.enemy.1.type = shooting
wave.2.enemy.1.arrivalTime = 30
wave.2.enemy.1.posX = 600.0
wave.2.enemy.1.movementSpeed = 3

wave.2.enemy.2.type = strafing
wave.2.enemy.2.arrivalTime = 120
wave.2.enemy.2.posX = 400.0
wave.2.enemy.2.movementSpeed = 8

wave.2.powerup.0.type = cooldown
wave.2.powerup.0.arrivalTime = 300
wave.2.powerup.0.posX = 400.0

# WAVE 3: Absolute Chaos
wave.3.enemy.0.type = strafing
wave.3.enemy.0.arrivalTime = 10
wave.3.enemy.0.posX = 100.0
wave.3.enemy.0.movementSpeed = 7

wave.3.enemy.1.type = strafing
wave.3.enemy.1.arrivalTime = 10
wave.3.enemy.1.posX = 700.0
wave.3.enemy.1.movementSpeed = 7

wave.3.enemy.2.type = shooting
wave.3.enemy.2.arrivalTime = 150
wave.3.enemy.2.posX = 400.0
wave.3.enemy.2.movementSpeed = 2
wave.3.enemy.shooting.firingRate = 25

wave.3.enemy.3.type = regular
wave.3.enemy.3.arrivalTime = 200
wave.3.enemy.3.posX = 300.0
wave.3.enemy.3.movementSpeed = 10

wave.3.enemy.4.type = regular
wave.3.enemy.4.arrivalTime = 200
wave.3.enemy.4.posX = 500.0
wave.3.enemy.4.movementSpeed = 10

wave.3.powerup.0.type = shield
wave.3.powerup.0.arrivalTime = 100
wave.3.powerup.0.posX = 400.0
