# PLAYER STATS
player.initialLives = 3
player.speed = 6
player.shootCooldown = 25
player.hitInvincibilityTime = 60
player.image = player.png
player.posY = 50.0

# SCORING
score.gotHit = 50
score.gotPowerup = 100
score.destroyedEnemy.regular = 25
score.destroyedEnemy.strafing = 50
score.destroyedEnemy.shooting = 75
score.hitProjectile = 10
score.waveCompleted = 250

# WAVE 1: Standard enemy speed
wave.1.enemy.0.type = regular
wave.1.enemy.0.arrivalTime = 30
wave.1.enemy.0.posX = 200.0
wave.1.enemy.0.movementSpeed = 4

wave.1.enemy.1.type = strafing
wave.1.enemy.1.arrivalTime = 120
wave.1.enemy.1.posX = 600.0
wave.1.enemy.1.movementSpeed = 4

wave.1.powerup.0.type = cooldown
wave.1.powerup.0.arrivalTime = 400
wave.1.powerup.0.posX = 400.0

# WAVE 2: Coordinated attack
wave.2.enemy.0.type = shooting
wave.2.enemy.0.arrivalTime = 60
wave.2.enemy.0.posX = 400.0
wave.2.enemy.0.movementSpeed = 2
enemy.shooting.firingRate = 90

wave.2.enemy.1.type = strafing
wave.2.enemy.1.arrivalTime = 60
wave.2.enemy.1.posX = 100.0
wave.2.enemy.1.movementSpeed = 4

wave.2.enemy.2.type = strafing
wave.2.enemy.2.arrivalTime = 60
wave.2.enemy.2.posX = 700.0
wave.2.enemy.2.movementSpeed = 4

wave.2.powerup.0.type = shield
wave.2.powerup.0.arrivalTime = 300
wave.2.powerup.0.posX = 400.0

# WAVE 3: The Swarm
wave.3.enemy.0.type = regular
wave.3.enemy.0.arrivalTime = 30
wave.3.enemy.0.posX = 150.0
wave.3.enemy.0.movementSpeed = 5

wave.3.enemy.1.type = regular
wave.3.enemy.1.arrivalTime = 60
wave.3.enemy.1.posX = 300.0
wave.3.enemy.1.movementSpeed = 5

wave.3.enemy.2.type = regular
wave.3.enemy.2.arrivalTime = 90
wave.3.enemy.2.posX = 450.0
wave.3.enemy.2.movementSpeed = 5

wave.3.enemy.3.type = regular
wave.3.enemy.3.arrivalTime = 120
wave.3.enemy.3.posX = 600.0
wave.3.enemy.3.movementSpeed = 5

wave.3.powerup.0.type = life
wave.3.powerup.0.arrivalTime = 250
wave.3.powerup.0.posX = 400.0
